const DAO = {
  getInitialBacklog() {
    return [
      {
        "id": 1,
        "description": "Users can exchange emails securely with predefined recipients.",
        "totalTime": 24,
        "remainTime": 24,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 2,
        "description": "Users can send large files securely.",
        "totalTime": 21,
        "remainTime": 21,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 3,
        "description": "Users can set time limits on emails for reading.",
        "totalTime": 27,
        "remainTime": 27,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 4,
        "description": "Users can send emails securely to unspecified recipients.",
        "totalTime": 30,
        "remainTime": 30,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 5,
        "description": "Administrators of organizations can monitor emails.",
        "totalTime": 16,
        "remainTime": 16,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 6,
        "description": "Each organization can set security policies and define recipients groups.",
        "totalTime": 24,
        "remainTime": 24,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 7,
        "description": "Users can manage their emails effectively.",
        "totalTime": 43,
        "remainTime": 43,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 8,
        "description": "Users and administrators can backup emails securely.",
        "totalTime": 23,
        "remainTime": 23,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 9,
        "description": "Users and administrators can delete emails completely.",
        "totalTime": 36,
        "remainTime": 36,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 10,
        "description": "Users can access emails from mobile.",
        "totalTime": 68,
        "remainTime": 68,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 11,
        "description": "Users can send short messages securely to each other.",
        "totalTime": 28,
        "remainTime": 28,
        "isBlocked": false,
        "isChosen": false,
      },
      {
        "id": 12,
        "description": "Users don’t want to receive spam-letters.",
        "totalTime": 24,
        "remainTime": 24,
        "isBlocked": false,
        "isChosen": false,
      },
    ];
  },
};

export default DAO;
